---
- name: Common setup for all nodes
  hosts: all
  become: true
  roles:
    - common
  # Common setup for all nodes

- name: Configure master nodes
  hosts: master
  become: true
  roles:
    - master
  # Configure master nodes

- name: Configure worker nodes
  hosts: worker
  become: true
  roles:
    - worker
  # Configure worker nodes

- name: Configure storage nodes
  hosts: storage
  become: true
  roles:
    - storage
  # Configure storage nodes

- name: Configure admin node
  hosts: admin
  become: true
  roles:
    - admin
  # Configure admin node

- name: Deploy monitoring stack
  hosts: master[0]
  become: true
  roles:
    - monitoring
  # Deploy monitoring stack

- name: Install RKE2 Cluster
  hosts: admin
  gather_facts: true
  roles:
    - ssh
  # Install RKE2 Cluster

- name: Download RKE2
  hosts: servers,agents,longhorn
  gather_facts: true
  roles:
    - rke2-download
  # Download RKE2

- name: Deploy Kube VIP
  hosts: servers
  gather_facts: true
  roles:
    - kube-vip
  # Deploy Kube VIP

- name: Prepare RKE2 on Servers and Agents
  hosts: servers,agents,longhorn
  gather_facts: true
  roles:
    - rke2-prepare
  # Prepare RKE2 on Servers and Agents

- name: Add additional RKE2 Servers and Agents
  hosts: servers,agents,longhorn
  gather_facts: true
  roles:
    - rke2
  # Add additional RKE2 Servers and Agents

- name: Apply manifests and security configurations
  hosts: servers
  gather_facts: true
  roles:
    - kubernetes
  # Apply manifests and security configurations

- name: Install Helm repositories and deploy charts
  hosts: admin
  gather_facts: true
  roles:
    - helm
  # Install Helm repositories and deploy charts
