---
- name: Create security namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: security-system

- name: Deploy Network Policies
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'network-policies.yaml.j2') | from_yaml_all | list }}"

- name: Deploy Pod Security Policies
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'pod-security-policies.yaml.j2') | from_yaml_all | list }}"

- name: Deploy Falco
  kubernetes.core.helm:
    name: falco
    chart_ref: falco-security/falco
    release_namespace: security-system
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'falco-values.yaml.j2') | from_yaml }}"
    create_namespace: true
    wait: yes

- name: Deploy RBAC configurations
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'rbac.yaml.j2') | from_yaml_all | list }}"
