---
- name: Restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
    daemon_reload: true
  when: inventory_hostname in groups['agents'] or inventory_hostname in groups['longhorn']
