---
- name: Install storage prerequisites
  apt:
    name:
      - open-iscsi
      - nfs-common
      - lvm2
    state: present

- name: Enable and start iscsid service
  systemd:
    name: iscsid
    state: started
    enabled: yes

- name: Configure RKE2 agent for storage nodes
  template:
    src: storage-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0644'

- name: Start RKE2 agent service on storage nodes
  systemd:
    name: rke2-agent
    state: started
    enabled: yes
