---
- name: Deploy RKE2 Agent Configuration
  ansible.builtin.template:
    src: templates/rke2-agent-config.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['agents'] or inventory_hostname in groups['longhorn']
  notify: Restart rke2-agent

- name: Ensure RKE2 agents are enabled
  ansible.builtin.systemd:
    name: rke2-agent
    enabled: true
    state: started
    daemon_reload: true
  when: inventory_hostname in groups['agents'] or inventory_hostname in groups['longhorn']
