---
# Add Helm repositories
- name: Add required Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  loop: "{{ helm_repos }}"

# Cert-Manager
- name: Deploy Cert-Manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'cert-manager-values.yaml.j2') | from_yaml }}"
    wait: yes

- name: Deploy ClusterIssuers
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'cluster-issuers.yaml.j2') | from_yaml_all | list }}"
  when: cert_manager_create_cluster_issuer | bool

# MetalLB
- name: Deploy MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'metallb-values.yaml.j2') | from_yaml }}"

- name: Configure MetalLB AddressPools
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'metallb-pools.yaml.j2') | from_yaml }}"

# Longhorn Storage
- name: Deploy Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'longhorn-values.yaml.j2') | from_yaml }}"

# ArgoCD
- name: Deploy ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'argocd-values.yaml.j2') | from_yaml }}"

# Vault
- name: Deploy Vault
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: vault
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'vault-values.yaml.j2') | from_yaml }}"

# Velero
- name: Deploy Velero
  kubernetes.core.helm:
    name: velero
    chart_ref: vmware-tanzu/velero
    release_namespace: velero
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'velero-values.yaml.j2') | from_yaml }}"

# Istio
- name: Deploy Istio
  kubernetes.core.helm:
    name: istio
    chart_ref: istio/istiod
    release_namespace: istio-system
    create_namespace: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values: "{{ lookup('template', 'istio-values.yaml.j2') | from_yaml }}"
